### ISSUE TITLE
Default Screen does not seem to kick in.

### ISSUE THREAD

**Issue by PatrykSzczerbinski** [ue4plugins/LoadingScreen#2]
Hi,

We are using this plugin for our multi platform game that we are developing.

We ran into a problem where the startup screen works fine and shows up at the correct time, but unfortunately, the default screen does not show up at all when changing in-between maps.

Do you have any ideas why this would be happening?
Let me know if you have any tips for us to try to get this issue fixed.

Thank you and regards.

EDIT: It does work on some levels every time but on some it doesn't at all.

**Comment by varomix** [comment]
Hi
Same problem here
the startup screen shows but not the Default between maps

Thanks

**Comment by KevinSoares** [comment]
Also having the same issue works when loading into the game but as soon as you try to load another map its a no go

**Comment by nickdarnell** [comment]
Hmm, does anything show up?  No text, no loading throbber?  Just black?

**Comment by varomix** [comment]
I get nothing, I added a LOG message in the code and I can see that log but nothing else, I was trying to figure it out but got busy doing something else, that's all I tested

**Comment by PatrykSzczerbinski** [comment]
We get nothing as well. I'm not sure but it seems like it either is being overwritten(if that's possible), or it just doesn't start the Movie... I'm not too sure what is happening.

**Comment by nickdarnell** [comment]
Are all of you using movies, or just text/texture?

**Comment by varomix** [comment]
I'm just using an image plus text

**Comment by PatrykSzczerbinski** [comment]
Sorry, we are just using a text and a throbber.

**Comment by nickdarnell** [comment]
Looks like it's going to require some improvements to the movie player.

**Comment by PatrykSzczerbinski** [comment]
That doesn't sound like a quick fix. Do you know when we could be expecting something that might get it working again? Thanks

**Comment by nickdarnell** [comment]
Will fix it in 4.12 - basically need to add an event to movie player to request setup of the loading screen if it hasn't been already setup when it attempts to launch the load screen.  Depending on PreMapLoad is basically the problem, because you're dependent on the call order of the delegate to setup the movie player before it gets called.

**Comment by feuxphep** [comment]
I'm also having issues with the Default between maps screen.  However, I noticed some strange behavior that no one mentioned.  I find that it will actually display every other time you do an open command.  I loaded a map from my main menu and it didn't display.  Then I disconnected (loading the MainMenu map) and it displayed.  At first I thought it was something special with my MainMenu map.  But that is not the case.  When I traveled around with "open" commands I found the loading screen displayed on alternating "open" commands.  So one time it displays, next time it doesn't, rinse, repeat.  This might be the behavior OP mentions when he says it works on "some" maps.

**Comment by nickdarnell** [comment]
yeah, that matches what i would expect, because of the order, it's setting up the -next- map, instead of the current map, because of the PreLoadMap call order.

**Comment by CHADALAK1** [comment]
Strange on my end, none of the visuals is showing for the load map on mine. No Text, no image, no movies being played. I did check the PreLoad and PostLoad debug checks and they are being called.... just for some reason nothing is happening visually

**Comment by PatrykSzczerbinski** [comment]
Nick, 

Can we only grab the CL# 2959701 from Perforce if we are on 4.11.2? Would only grabbing this changelist make the loading screens working or do we need to grab the whole 4.12 update?

Thanks

**Comment by nickdarnell** [comment]
Sure - but it won't just fix everything.  It requires changes to this plugin to take advantage of the improvements, been waiting to add those fixes to github until 4.12 is closer to completion.

**Comment by nickdarnell** [comment]
There are some other issues I'm investigating that I plan to find some time to solve some night - my choice to use UFonts might be a problem.  if the UFont is first loaded on the main thread, the linker remembers the thread it was loaded on - and explodes when it attempts to load the bulk data containing the ttf data.  So... gota do something about that.

**Comment by PatrykSzczerbinski** [comment]
Sounds good. Thanks a lot for this, will be waiting for the fix. I guess 4.12 will not come out for the next couple of weeks anyway right?

**Comment by Kenomica** [comment]
Just found this plugin - and although it is not working with any map changes / default screen, seeing how it how it works with the startup screen looks great. Thanks for all the work you're putting in to it, I look forward to the 4.12 version.

**Comment by Hevedy** [comment]
4.12 released, now what ? :)

**Comment by nickdarnell** [comment]
Pushed out some changes - should work in 4.12 now.

**Comment by Hevedy** [comment]
@nickdarnell thanks you!

**Comment by Kenomica** [comment]
@nickdarnell Thanks! Excited to use this!

**Comment by Kenomica** [comment]
It certainly works now, however whenpackaging (Win32 or 64 Shipping) I get the error 

"Assertion failed: IsValid() [File:D:\Build\++UE4+Release-4.12+Compile\Sync\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h] [Line: 728]"

and the package fails.

Also, I noticed that the font and font size no longer actually change anything.

**Comment by nickdarnell** [comment]
Callstack?  The font thing is expected - if it is causing cross thread problems from the linker being used on two threads.

**Comment by Kenomica** [comment]
@nickdarnell - Thanks for the reply. Really appreciate your work on this.

It's definitely this plugin causing the package fail. When disabled, the game packages fine - (I use other plugins such as Rama's Victory Plugin, Fmod,etc.)

There is no crash, the loading screen works great when playing in standalone through the editor (Doesn't show up in PIE, but I think I recall that being intended behaviour) but I cannot package the game.

I've attached the Output Log.

[Output Log.txt](https://github.com/ue4plugins/LoadingScreen/files/342369/Output.Log.txt)

**Comment by nickdarnell** [comment]
It's crashing - cooking happens in another process, so it's just silently dying :)  Odd that there's no callstack, though are you on a binary build with no symbols downloaded from the launcher?

**Comment by Kenomica** [comment]
Ah, okay. I Never realised that.

Yeah, binary build - just checked and no symbols downloaded. I'll download the symbols and check again.

**Comment by nickdarnell** [comment]
Fixed.  Was crashing because slate app wasn't initialized and I forgot to check.
