### ISSUE TITLE
Error with 4.15 and 4.16

### ISSUE THREAD

**Issue by OAXP** [ue4plugins/LoadingScreen#20]
When I try to Generate project with the plugin, I always get an error(french) :
Running C:/Program Files/Epic Games/UE_4.15/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="C:/Users/OAXP/Desktop/MY GAME !/GAME PROJECT/Parkour/---- 415/ALCS/Parkour_V3.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
Messages while compiling C:\Users\OAXP\Desktop\MY GAME !\GAME PROJECT\Parkour\---- 415\----\Intermediate\Build\BuildRules\Parkour_V3ModuleRules.dll:
c:\Users\OAXP\Desktop\MY GAME !\GAME PROJECT\Parkour\---- 415\ALCS\Plugins\LoadingScreen-master\Source\LoadingScreen\LoadingScreen.Build.cs(8,15) : error CS1729: 'UnrealBuildTool.ModuleRules' ne contient pas un constructeur qui accepte des arguments 1
UnrealBuildTool Exception: ERROR: UnrealBuildTool encountered an error while compiling source files

**Comment by HughieDM** [comment]
I Had the same issue. 
If you remove ": base(Target)" from line 8 in LoadingScreen.Build.cs it should work
If you upgrade to 4.16 you will have to put that back in

**Comment by OAXP** [comment]
OMG thanks man ! :D

**Comment by OAXP** [comment]
Hey I have another problem when I activate the plugin : Running C:/Program Files/Epic Games/UE_4.15/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="C:/Users/OAXP/Desktop/MY GAME !/GAME PROJECT/Parkour/ALCS 415/ALCS/Parkour_V3.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
ERROR: Unable to instantiate instance of 'LoadingScreen' object type from compiled assembly 'Parkour_V3ModuleRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.  Unreal Build Tool creates an instance of your module's 'Rules' object in order to find out about your module's requirements.  The CLR exception details may provide more information:  System.MissingMethodException: Le constructeur sur le type 'UnrealBuildTool.Rules.LoadingScreen' est introuvable.
   ? System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   ? System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   ? System.Activator.CreateInstance(Type type, Object[] args)
   ? UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, TargetInfo Target, FileReference& ModuleFileName)

**Comment by OAXP** [comment]
My issue in 4.16 is : Parkour_V3 could not be compiled. Try rebuild it from source manually.

**Comment by HughieDM** [comment]
well that fix I told you about did allow me to Generate the Visual Studio files but After Building,activating the plugin, and restarting I also got the failed to build.
So I tryed to revert all the changes to 4.16 and I got a bunch of errors. So Ill let you know when I find out more.

**Comment by OAXP** [comment]
Ok thanks :D

**Comment by HughieDM** [comment]
Ok so I figured it out and I was correct I just forgot to fix some past thing that I did.

You just have to undo all of the most recent commit.

In LoadingScreen.Build.cs
Change:
7		public LoadingScreen(ReadOnlyTargetRules Target)
8            : base(Target)
to:
7		public LoadingScreen(TargetInfo Target)

In LoadingScreenSettings.cpp
Add
#include "LoadingScreenPrivatePCH.h"

In SSimpleLoadingScreen.cpp
Add
#include "SSimpleLoadingScreen.h"

**Comment by OAXP** [comment]
For 4.16 or 4.15 ?

**Comment by OAXP** [comment]
In 4.16 I always get The error could not be compiled...

**Comment by OAXP** [comment]
4.15 too

**Comment by OAXP** [comment]
I'll try to delete : Binaries, Build, Intermediate, Saved, .sln, .vs files and rebuild the project

**Comment by gabz123** [comment]
did it work for you guys?

**Comment by HughieDM** [comment]
Sorry I totally miss all of these yes it did work for us on 4.15, But with 4.16 it should work with the most recent version of the load screen plugin. We are currently updating too 4.16 and will let you know how it goes

**Comment by gabz123** [comment]
i am sorry to bother but is it possible if you can provide a screenshot of the code should look on Vs Cause I am still getting errors

**Comment by OAXP** [comment]
Me too :( can't install the plugin, give us an example project with the plugin, like ThirdPersonExample project with this plugin. And do you have the source version of UE4 ?

**Comment by HughieDM** [comment]
If your using 4.16 the only thing you have to fix is in LoadingScreenSettings.cpp and SSimpleLoadingScreen.cpp add at the top **#include "LoadingScreenPrivatePCH.h"**

If you are using 4.15 
in LoadingScreen.Build.cs
change **public LoadingScreen(ReadOnlyTargetRules Target)** to **public LoadingScreen(TargetInfo Target)**
and delete **: base(Target)**

next do the same that would be done for 4.16 as mentioned above

**Comment by OAXP** [comment]
Please copy and paste the entire code for 4.16 and 4.15.

**Comment by OAXP** [comment]
Thanks HughieDM worked on 4.16, I'll try now on 4.15.

**Comment by OAXP** [comment]
Don't work for 4.15

**Comment by OAXP** [comment]
OMG thanks worked for 4.15 too ! :D

**Comment by nickdarnell** [comment]
Should be fixed in 4.16 now.
