### ISSUE TITLE
[SOLVED]UE4.16 Not building from Source

### ISSUE THREAD

**Issue by mrjamesweston** [ue4plugins/LoadingScreen#25]
https://gyazo.com/72427a1df37c6d9924dbf626e2bd2eb2
That's what I get when trying to build from source.

**Comment by metahusk** [comment]
This commit worked for me: https://github.com/ue4plugins/LoadingScreen/commit/0bf8d72516f1f0e60dfeab1878083f4b199b8c04

**Comment by mrjamesweston** [comment]
I've gone ahead and added those commits to my files, will try to rebuild. Thank you!
