### ISSUE TITLE
Plugin for 4.17 

### ISSUE THREAD

**Issue by fn2505** [ue4plugins/LoadingScreen#27]
Hello everyone, how can I make this plugin compatible with version 4.17.1 of the engine?

**Comment by HoaxXx** [comment]
1. create a c++ project via the launcher
2. copy the plugin to the new project's plugin folder (create one)
3. open the "LoadingScreen.uplugin" file with a text editor, replace "4.16.0" with "4.17.0" (it's optional, but will save you a warning prompt)
4. open the new project's .snl file with Visiau Studio
5. build project in Visual Studio (right click on project name in Solution Explorer pane)
6. if it fails, repeat 5. but run "clean" instead, then run "build"

Don't forget to enable plugin in UE4 settings afterwards.

**Comment by fn2505** [comment]
I followed your guide, then to use the plugin in another project, I copied the "plugins" folder, but when I start packing, the process fails
