### ISSUE TITLE
Unreal 4.20

### ISSUE THREAD

**Issue by IppolitoGermer** [ue4plugins/LoadingScreen#35]
I can not compile for 4.20. Some ideas?

**Comment by FynjyAC** [comment]
Replace function
`virtual void AddReferencedObjects(FReferenceCollector& Collector) override
	{
		UObject* localResourceObject = FSlateBrush::GetResourceObject();
		if (localResourceObject)
		{
			Collector.AddReferencedObject(localResourceObject);
		}
	}`

**Comment by aidne** [comment]
Thank you very much!
