### ISSUE TITLE
4.20 Version ?

### ISSUE THREAD

**Issue by lucasdlk** [ue4plugins/LoadingScreen#37]
I seems this plugin doesn't compile anymore...
Can you do a 4.20 version, or tell me how to workaround with errors messages ?

**Comment by jonathancumming** [comment]
HI, I can help you out.

here are two new files, replace the existing ones. Its simply changing the brush used for the loading image to use FDeferredCleanupSlateBrush.
(note: there are a few other small changes in these files, but it should be good enough to help you out)

GL.

[Private.zip](https://github.com/ue4plugins/LoadingScreen/files/2354383/Private.zip)

**Comment by Piepants** [comment]
Thanks a ton for this. :)

**Comment by Predatorzgz** [comment]
Yes you rules!

**Comment by elec2ron** [comment]
Thanks for this version. 

Only problem is i am getting the start up loading screen but none when opening a map in standalone or a packaged build. 

Not sure if its a problem with this 420 version or something more general with the plugin.

**Comment by elec2ron** [comment]
Yes i am testing with standalone play in editor and a packaged build. I was under the impression the loading screen should also play while a new map is loading but it only ever plays at start up for me.
